plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.5-SNAPSHOT'
description = 'Task_Manager'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    
    // H2
    runtimeOnly 'com.h2database:h2'
    
    // PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    testImplementation 'org.springframework.security:spring-security-test'


    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation "org.testcontainers:postgresql"

    // fix for "Could not find a valid Docker environment"
    //testImplementation 'org.testcontainers:testcontainers:2.0.2'
    testImplementation 'org.testcontainers:testcontainers:1.21.4'
}
tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// Настройка PostgreSQL
bootRun {
    systemProperty 'spring.profiles.active', 'prod'
}

springBoot {
    buildInfo()
}

test {
    systemProperty "spring.profiles.active", "test"
}
