version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: task_manager_postgres
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskmanager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../src_db_init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: