ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS created_by BIGINT;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS updated_by BIGINT;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS deleted_by BIGINT;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;